child1_birth = ('RAMU', 'KOTI METERNITY HOSPITAL', 'KOTI', 'HYDERABAD', '10/08/2002', 'SECOND')
child2_birth = ('Sai','MARUTHI HOSPITAL', 'CHAMPAPET', 'HYDERABAD', '02/09/1999', 'FIRST')
type(child1_birth)
type(child2_birth)
print(child1_birth)
print(child2_birth)
print("Child 1 Name:", child1_birth[0])
print("Child 2 Name:", child2_birth[0])
print("Child 1 Birth Date:", child1_birth[4])
print("Child 2 Birth Date:", child2_birth[4])
